### ISSUE TITLE
Add Linux Support

### ISSUE THREAD

**Issue by PauloHFS** [brunocroh/notify-me#1]
I do a little research and I find out that linux shells uses the [freedesktop specifications to implements notifications](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html). The major uses the `libnotification` that has the `notify-send`utility that we can use to support linux.

What you think? May I implement this if you like the idea.

**Comment by brunocroh** [comment]
I believe it can be a bit complicated.

Maybe try to use some package that already do it for us can be better, like [dunst](https://github.com/dunst-project/dunst) can turn it more easy, what do you think?

And of course if you could work on that will be amazing, I did not have a Linux here to test it.

**Comment by PauloHFS** [comment]
We can use this https://www.npmjs.com/package/node-notifier 

What you think?

**Comment by brunocroh** [comment]
Wow, this package literally does the same thing that I propose to do, I will add it to the README as a recommendation alternative, but of course if we want to have the same feature we can look how they implement it and try to do something similar here
