### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by reginaldosnunes** [brunocroh/notify-me#3]
I'm trying to implement Windows support, my solution is based on the use of a PowerShell script, but as I don't have much experience I'm having difficulty getting the script to be copied to the build folder, would you have any suggestions to solve this problem?

**Comment by brunocroh** [comment]
You can create a js script to move a file on the build step script on the package json, if you already have the powershell script to send notification, please create a PR with it, and I can help you to do this part, what do you think?

**Comment by reginaldosnunes** [comment]
Sure! I'll submit a PR with my changes, including the PowerShell script. After that, we can work on the file-moving script.

**Comment by reginaldosnunes** [comment]
The implementation to add Windows support has been successfully merged #4. The functionality is now available and has been tested in the Windows environment. Special thanks to @brunocroh for their valuable contributions and review!

If there are any issues or additional questions, please feel free to comment. Otherwise, we'll consider this issue closed.
